spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Lottery?serverTimezone=UTC&useSSL=false
    username: rooty
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
